[package]
name = "rsut-math"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsa"
[[bin]]
name = "GF-GCM"

[dependencies]
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.15"
rand = "0.8.5"
