name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Move
      run: |
       mkdir -p ./src/bin
       cp ./*.rs ./src/bin
# https://github.com/actions-rs/toolchain
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
