name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Move
      run: |
       mkdir -p ./src/bin
       cp ./*.rs ./src/bin
    - name: Build
      run: cargo build --verbose
